package com.codex.ringlab;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.content.res.ColorStateList;import android.view.*;import android.widget.*;
public class AboutActivity extends Activity {
    private static final int INK=0xff24364d,MUTED=0xff6e7e91,PAPER=0xfff5f7fc,NIGHT=0xff16243b,ACCENT=0xffd85371;
    private static final String LATEST=MainActivity.REPOSITORY+"/releases/latest";
    private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private int px(float n){return Math.round(n*getResources().getDisplayMetrics().widthPixels/1600f);}
    private GradientDrawable bg(int color,int radius){GradientDrawable b=new GradientDrawable();b.setColor(color);b.setCornerRadius(px(radius));return b;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
    private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(3),1);return t;}
    private Button button(String label,int color,int ink,Runnable action){return StudioUi.button(this,label,color,ink,action);}
    private LinearLayout card(LinearLayout parent,String heading){LinearLayout box=column();box.setPadding(px(24),px(24),px(24),px(24));box.setBackground(bg(Color.WHITE,40));LinearLayout.LayoutParams layout=new LinearLayout.LayoutParams(-1,-2);layout.bottomMargin=dp(12);parent.addView(box,layout);TextView title=text(heading,17,INK);title.setTypeface(Typeface.create("sans-serif-medium",0));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.bottomMargin=dp(9);box.addView(title,hp);return box;}
    private void body(LinearLayout card,String value){card.addView(text(value,13,MUTED));}
    private void action(LinearLayout box,String label,int color,int ink,Runnable click){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(38));p.topMargin=px(24);box.addView(button(label,color,ink,click),p);}
    private void open(String link){try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(link)));}catch(Exception e){copy(link);Toast.makeText(this,"未找到浏览器，链接已复制",Toast.LENGTH_LONG).show();}}
    private void copy(String value){((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("灯环工坊",value));Toast.makeText(this,"链接已复制",Toast.LENGTH_SHORT).show();}
    private void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894);}
    @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(focus)immersive();}
    @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_FULLSCREEN);immersive();
        LinearLayout root=new LinearLayout(this);root.setBackgroundColor(PAPER);root.setPadding(px(20),px(20),px(20),px(20));
        ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout cards=column();cards.setPadding(px(56),0,dp(14),0);scroll.addView(cards);root.addView(scroll,new LinearLayout.LayoutParams(0,-1,2.05f));
        LinearLayout intro=card(cards,"关于灯环工坊");body(intro,"支付宝 N5 系列碰一碰设备专用的灯环控制软件。");body(intro,"已测试：改装 N5D · LineageOS Android 11 · Magisk Root。其他设备与原厂系统尚未完成兼容验证。");
        LinearLayout repository=card(cards,"开源项目");LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);ImageView github=new ImageView(this);try(java.io.InputStream in=getAssets().open("github.png")){github.setImageBitmap(BitmapFactory.decodeStream(in));}catch(Exception ignored){}github.setContentDescription("GitHub");row.addView(github,new LinearLayout.LayoutParams(dp(26),dp(26)));TextView repo=text("Cyber-Yichen / N5D-RingStudio",14,INK);repo.setPadding(dp(10),0,0,0);row.addView(repo);repository.addView(row);row.setOnClickListener(v->open(MainActivity.REPOSITORY));action(repository,"打开 GitHub 项目",Color.WHITE,INK,()->open(MainActivity.REPOSITORY));action(repository,"复制仓库链接",Color.WHITE,MUTED,()->copy(MainActivity.REPOSITORY));
        LinearLayout api=card(cards,"其他应用控制灯光");body(api,"允许本机应用调用灯效、独立 Logo 和自定义灯光帧。开启后，任何本机应用都可短暂借用，用完平滑恢复原灯效；主界面可随时接管。");Switch enabled=new Switch(this);enabled.setText("开放本机灯光接口");enabled.setTextSize(14);enabled.setTextColor(INK);enabled.setThumbTintList(ColorStateList.valueOf(ACCENT));enabled.setChecked(getSharedPreferences("effects",0).getBoolean("api_enabled",false));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(44));sp.topMargin=dp(6);api.addView(enabled,sp);enabled.setOnCheckedChangeListener((v,on)->{getSharedPreferences("effects",0).edit().putBoolean("api_enabled",on).apply();if(!on&&EffectsService.apiActive)startService(new Intent(this,EffectsService.class).putExtra("command","api_disable"));});action(api,"查看接口文档",Color.WHITE,INK,()->open(MainActivity.REPOSITORY+"/blob/main/docs/control-api.md"));
        LinearLayout free=card(cards,"免费声明");body(free,"本软件永久免费、开源，没有付费版本、激活码或收费渠道。若付费购买本软件，说明你已上当受骗。请从 GitHub 项目仓库免费下载。");
        LinearLayout disclaimer=card(cards,"免责声明");body(disclaimer,"这是个人项目，与支付宝及设备厂商无隶属或授权关系。软件按现状提供；Root 和底层灯光控制存在风险。其他型号、主板和系统不保证兼容。请确认设备归属、接口与供电，出现异常应停止使用。在适用法律允许的范围内，作者不承担使用、修改或设备故障造成的损失与责任。许可条款见仓库 LICENSE。");action(disclaimer,"查看许可与完整说明",Color.WHITE,INK,()->open(MainActivity.REPOSITORY+"#免责与使用风险"));
        LinearLayout brand=column();brand.setGravity(Gravity.CENTER_HORIZONTAL);brand.setPadding(px(24),px(24),px(24),px(24));brand.setBackground(bg(NIGHT,40));root.addView(brand,new LinearLayout.LayoutParams(0,-1,1));
        ImageView icon=new ImageView(this);try(java.io.InputStream in=getAssets().open("app-logo.png")){icon.setImageBitmap(BitmapFactory.decodeStream(in));}catch(Exception ignored){}icon.setContentDescription("灯环工坊应用 Logo");icon.setScaleType(ImageView.ScaleType.FIT_CENTER);icon.setBackground(bg(NIGHT,40));icon.setClipToOutline(true);brand.addView(icon,new LinearLayout.LayoutParams(dp(122),dp(122)));
        TextView name=text("N5D 灯环工坊",21,Color.WHITE);name.setTypeface(Typeface.create("sans-serif-medium",0));name.setGravity(Gravity.CENTER);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,-2);np.topMargin=dp(8);brand.addView(name,np);
        TextView version=text("1.2",14,0xff92aacb);version.setTypeface(Typeface.MONOSPACE);version.setGravity(Gravity.CENTER);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-2,-2);vp.topMargin=dp(5);brand.addView(version,vp);
        TextView author=text("Cyber-Yichen",14,0xffbac8dd);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-2,-2);ap.topMargin=dp(8);brand.addView(author,ap);
        brand.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));LinearLayout dock=column();brand.addView(dock,new LinearLayout.LayoutParams(-1,-2));dock.addView(button("检查更新",ACCENT,Color.WHITE,()->open(LATEST)),new LinearLayout.LayoutParams(-1,dp(38)));LinearLayout.LayoutParams logLayout=new LinearLayout.LayoutParams(-1,dp(38));logLayout.topMargin=px(24);dock.addView(button("更新日志",0xff233650,0xffbac8dd,()->ReleaseNotes.show(this)),logLayout);LinearLayout.LayoutParams returnLayout=new LinearLayout.LayoutParams(-1,dp(38));returnLayout.topMargin=px(24);dock.addView(button("返回灯效",0xff233650,0xffe4edfb,()->finish()),returnLayout);setContentView(root);
    }
}
