package com.codex.ringlab;
import android.os.*;import org.json.*;
final class ControlProtocol {
    static final int VERSION=1,HELLO=1,STATE=2,ACQUIRE=10,EFFECT=11,FRAME=12,LOGO=13,KEEPALIVE=14,RELEASE=15,OFF=16;
    static final String ACTION="com.codex.ringlab.CONTROL";
    static final class Error extends Exception {final String code;Error(String code,String message){super(message);this.code=code;}}
    static int integer(Bundle b,String key,int fallback,int min,int max)throws Error{if(b.containsKey(key)&&!(b.get(key) instanceof Integer))throw new Error("INVALID_ARGUMENT",key+" 必须是 int");int n=b.getInt(key,fallback);if(n<min||n>max)throw new Error("INVALID_ARGUMENT",key+" 超出范围 "+min+"～"+max);return n;}
    static void reply(Message request,boolean ok,String code,String detail,JSONObject data){if(request.replyTo==null)return;try{Message response=Message.obtain(null,request.what);response.arg1=request.arg1;Bundle b=new Bundle();b.putInt("api_version",VERSION);b.putBoolean("ok",ok);b.putString("code",code);b.putString("message",detail);if(data!=null)b.putString("data",data.toString());response.setData(b);request.replyTo.send(response);}catch(Exception ignored){}}
    static JSONObject capabilities(boolean enabled)throws JSONException{JSONObject j=new JSONObject();j.put("api_version",VERSION);j.put("app_version","1.1");j.put("enabled",enabled);j.put("mapping_id","n5d-clockwise-2026-10");j.put("rgb_pixels",24);j.put("white_pixels",24);j.put("raw_channels",96);j.put("white_offset_degrees",7.5);j.put("maximum_fps",25);j.put("lease_min_ms",2000);j.put("lease_max_ms",60000);j.put("formats",new JSONArray(new String[]{"rgb_white","raw96"}));j.put("effects",new JSONArray(Patterns.IDS));j.put("palettes",new JSONArray(Patterns.PALETTES));j.put("features",new JSONArray(new String[]{"effect_settings","rgb_frames","white_frames","raw_channels","logo","state","lease","restore_local"}));return j;}
    static EffectSettings effect(Bundle b,EffectSettings current)throws Exception{String raw=b.getString("settings","{}");if(raw.length()>4096)throw new Error("INVALID_ARGUMENT","settings 过长");JSONObject j=new JSONObject(raw);IntentBuilder builder=new IntentBuilder();java.util.Iterator<String> keys=j.keys();JSONObject ranges=new JSONObject("{brightness:[0,255],white:[0,255],speed:[1,100],palette:[0,13],color_count:[1,8],bank:[0,2],source:[0,1],gain:[0,100],tail:[1,24],softness:[0,100],width:[8,80],waves:[1,6],density:[5,90],floor:[0,80],release:[0,100],gate:[30,85]}");
        while(keys.hasNext()){String k=keys.next();Object v=j.get(k);if("mode".equals(k)){if(!(v instanceof String)||!Patterns.valid((String)v))throw new Error("INVALID_ARGUMENT","未知灯效");builder.i.putExtra(k,(String)v);}else if("colors".equals(k)){if(!(v instanceof String))throw new Error("INVALID_ARGUMENT","colors 必须是 HEX 字符串");Patterns.parseColors((String)v);builder.i.putExtra(k,(String)v);}else if("reverse".equals(k)){if(!(v instanceof Boolean))throw new Error("INVALID_ARGUMENT","reverse 必须是布尔值");builder.i.putExtra(k,(Boolean)v);}else if(ranges.has(k)){JSONArray r=ranges.getJSONArray(k);if(!(v instanceof Number)||((Number)v).doubleValue()!=((Number)v).intValue()||((Number)v).intValue()<r.getInt(0)||((Number)v).intValue()>r.getInt(1))throw new Error("INVALID_ARGUMENT",k+" 数值无效");builder.i.putExtra(k,((Number)v).intValue());}else throw new Error("INVALID_ARGUMENT","未知设置 "+k);}
        return EffectSettings.read(builder.i,current);
    }
    private static final class IntentBuilder {final android.content.Intent i=new android.content.Intent();}
    static Patterns.Frame frame(Bundle b)throws Error{Patterns.Frame f=new Patterns.Frame();f.fade=integer(b,"brightness",255,0,255);f.whiteFade=integer(b,"white_brightness",255,0,255);String format=b.getString("format","rgb_white");
        if("raw96".equals(format)){byte[] raw=b.getByteArray("channels");if(raw==null||raw.length!=96)throw new Error("INVALID_ARGUMENT","channels 必须是 96 字节");for(int i=0;i<96;i++)f.channels[i]=raw[i]&255;}
        else if("rgb_white".equals(format)){byte[] rgb=b.getByteArray("rgb"),white=b.getByteArray("white");if(rgb==null||rgb.length!=72||white==null||white.length!=24)throw new Error("INVALID_ARGUMENT","rgb 必须是 72 字节，white 必须是 24 字节");for(int i=0;i<24;i++){int g=Patterns.RGB[i]*3;f.channels[g]=rgb[i*3+2]&255;f.channels[g+1]=rgb[i*3+1]&255;f.channels[g+2]=rgb[i*3]&255;f.channels[Patterns.WHITE[i]]=white[i]&255;}}
        else throw new Error("INVALID_ARGUMENT","未知帧格式");return f;
    }
}
