package com.codex.ringlab;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.content.res.ColorStateList;import android.view.*;import android.widget.*;
public class MainActivity extends Activity {
    private interface IntConsumer {void accept(int value);}
    static final String REPOSITORY="https://github.com/Cyber-Yichen/N5D-RingStudio";
    private static final int INK=0xff24364d,MUTED=0xff6e7e91,ACCENT=0xffd85371,PAPER=0xfff5f7fc,LINE=0xffe9edf5,NIGHT=0xff16243b;
    private final Handler ui=new Handler();private SharedPreferences prefs;private EffectSettings cfg;
    private boolean building,dead,categoryMusic;private LinearLayout controls,segments,colorSlots;private RingView ring;private TextView status,audio;private Button normalTab,musicTab,runButton;private ProgressBar meter;private Intent pending;
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private int screenPx(float n){return Math.round(n*getResources().getDisplayMetrics().widthPixels/1600f);}
    private GradientDrawable bg(int color,int radius){GradientDrawable b=new GradientDrawable();b.setColor(color);b.setCornerRadius(screenPx(radius));return b;}
    private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");return t;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
    private Button button(String label,int color,int ink,Runnable action){return StudioUi.button(this,label,color,ink,action);}
    private LinearLayout.LayoutParams cell(int height){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(height),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}
    private void section(String name){TextView t=text(name,16,INK);t.setTypeface(Typeface.create("sans-serif-medium",0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(30));p.topMargin=dp(9);controls.addView(t,p);}
    private void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894);}
    @Override public void onWindowFocusChanged(boolean focus){super.onWindowFocusChanged(focus);if(focus)immersive();}
    @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_FULLSCREEN);immersive();prefs=getSharedPreferences("effects",0);
        categoryMusic=prefs.getBoolean("category_music",Patterns.music(prefs.getString("mode","rainbow")));cfg=load(categoryMusic);
        LinearLayout root=new LinearLayout(this);root.setPadding(screenPx(20),screenPx(20),screenPx(20),screenPx(20));root.setBackgroundColor(PAPER);
        LinearLayout left=column();left.setPadding(0,0,dp(14),0);root.addView(left,new LinearLayout.LayoutParams(0,-1,2.05f));
        segments=new LinearLayout(this);segments.setPadding(dp(4),dp(4),dp(4),dp(4));segments.setBackground(bg(LINE,40));
        normalTab=button("普通灯效",LINE,MUTED,()->category(false));musicTab=button("音乐灯效",LINE,MUTED,()->category(true));segments.addView(normalTab,cell(37));segments.addView(musicTab,cell(37));LinearLayout.LayoutParams segmentLayout=new LinearLayout.LayoutParams(-1,dp(51));segmentLayout.setMargins(screenPx(56),0,screenPx(16),0);left.addView(segments,segmentLayout);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setVerticalScrollBarEnabled(false);controls=column();controls.setPadding(screenPx(56),0,screenPx(16),dp(12));scroll.addView(controls);left.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout preview=column();preview.setPadding(screenPx(24),screenPx(24),screenPx(24),screenPx(24));preview.setBackground(bg(NIGHT,40));root.addView(preview,new LinearLayout.LayoutParams(0,-1,1));
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView brand=text("灯环工坊",17,0xfff3f7ff);brand.setTypeface(Typeface.create("sans-serif-medium",0));bar.addView(brand,new LinearLayout.LayoutParams(0,dp(35),1));bar.addView(button("关于",0xff233650,0xffbac8dd,()->about()),new LinearLayout.LayoutParams(dp(57),dp(32)));preview.addView(bar);
        ring=new RingView(this);preview.addView(ring,new LinearLayout.LayoutParams(-1,0,1));
        status=text("准备灯光",12,0xffdce7f9);preview.addView(status);audio=text("",11,0xff92aacb);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(26));ap.topMargin=dp(5);preview.addView(audio,ap);
        meter=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);meter.setMax(100);meter.setProgressTintList(ColorStateList.valueOf(0xff57cdd1));preview.addView(meter,new LinearLayout.LayoutParams(-1,dp(4)));
        LinearLayout dock=new LinearLayout(this);runButton=button("开灯",ACCENT,Color.WHITE,()->toggleLights());LinearLayout.LayoutParams primary=new LinearLayout.LayoutParams(0,dp(38),1);primary.rightMargin=screenPx(24);dock.addView(runButton,primary);dock.addView(button("Logo 设置",0xff2c425e,0xffe4edfb,()->logoDialog()),new LinearLayout.LayoutParams(0,dp(38),1));LinearLayout.LayoutParams dockLayout=new LinearLayout.LayoutParams(-1,-2);dockLayout.bottomMargin=screenPx(24);preview.addView(dock,dockLayout);
        LinearLayout actions=new LinearLayout(this);LinearLayout.LayoutParams backLayout=new LinearLayout.LayoutParams(0,dp(38),1);backLayout.rightMargin=screenPx(24);actions.addView(button("后台",0xff233650,0xffbac8dd,()->moveTaskToBack(true)),backLayout);actions.addView(button("退出",0xff233650,0xffbac8dd,()->quit()),new LinearLayout.LayoutParams(0,dp(38),1));preview.addView(actions);

        setContentView(root);renderControls();ui.post(refresh);ui.postDelayed(()->{if(!EffectsService.ready&&!EffectsService.apiActive)applyRing(true);},350);ui.postDelayed(()->ReleaseNotes.firstLaunch(this),900);
    }
    private void toggleLights(){if(EffectsService.running)dispatch(new Intent(this,EffectsService.class).putExtra("command","off"));else applyRing(true);}
    private EffectSettings load(boolean music){String raw=prefs.getString(music?"music_settings":"normal_settings","");EffectSettings c=EffectSettings.fromJson(raw,music);
        if(raw.isEmpty()&&!music){c.brightness=prefs.getInt("brightness",96);c.speed=prefs.getInt("speed",40);c.palette=prefs.getInt("palette",7);c.bank=prefs.getInt("bank",0);}
        return c;
    }
    private void persist(){prefs.edit().putBoolean("category_music",categoryMusic).putString(categoryMusic?"music_settings":"normal_settings",cfg.json().toString()).apply();}
    private void category(boolean music){if(categoryMusic==music)return;persist();categoryMusic=music;cfg=load(music);renderControls();applyRing(true);}
    private void choose(String mode){cfg.mode=mode;renderControls();applyRing(true);}
    private void renderControls(){building=true;controls.removeAllViews();normalTab.setBackground(bg(categoryMusic?LINE:Color.WHITE,28));normalTab.setTextColor(categoryMusic?MUTED:INK);musicTab.setBackground(bg(categoryMusic?Color.WHITE:LINE,28));musicTab.setTextColor(categoryMusic?INK:MUTED);
        section(categoryMusic?"随音乐变化":"选择效果");LinearLayout row=null;int col=0;for(int n=0;n<Patterns.IDS.length;n++){if(Patterns.music(Patterns.IDS[n])!=categoryMusic)continue;if(col%5==0){row=new LinearLayout(this);controls.addView(row);}final String mode=Patterns.IDS[n];boolean selected=mode.equals(cfg.mode);Button b=button(Patterns.NAMES[n],selected?ACCENT:Color.WHITE,selected?Color.WHITE:INK,()->choose(mode));row.addView(b,cell(38));col++;}while(col%5!=0){row.addView(new View(this),cell(38));col++;}
        section("配色");LinearLayout colors=new LinearLayout(this);colors.addView(button(Patterns.PALETTES[cfg.palette]+"  ·  预设配色",Color.WHITE,INK,()->paletteDialog()),cell(38));LinearLayout count=column();colors.addView(count,new LinearLayout.LayoutParams(0,-2,1));slider(count,"颜色数量",1,8,cfg.colorCount," 色",v->{resizeColors(v);renderColorSlots();},()->changed());colors.setGravity(Gravity.CENTER_VERTICAL);controls.addView(colors);
        colorSlots=new LinearLayout(this);controls.addView(colorSlots);renderColorSlots();
        section("亮度与运动");LinearLayout strengths=new LinearLayout(this);LinearLayout a=column(),b=column();strengths.addView(a,new LinearLayout.LayoutParams(0,-2,1));strengths.addView(b,new LinearLayout.LayoutParams(0,-2,1));controls.addView(strengths);
        slider(a,"彩灯亮度",0,255,cfg.brightness,"",v->cfg.brightness=v,()->changed());
        slider(b,"白灯亮度",0,255,cfg.white,"",v->cfg.white=v,()->changed());
        LinearLayout banks=new LinearLayout(this);String[] regions={"彩灯","白灯","彩灯 + 白灯"};for(int i=0;i<3;i++){final int k=i;banks.addView(button(regions[i],cfg.bank==i?0xffdfe7f7:Color.WHITE,cfg.bank==i?0xff365b91:MUTED,()->{cfg.bank=k;renderControls();changed();}),cell(32));}controls.addView(banks);
        if(!categoryMusic&&!cfg.mode.equals("solid")){LinearLayout movement=new LinearLayout(this);LinearLayout sp=column();movement.addView(sp,new LinearLayout.LayoutParams(0,-2,2));slider(sp,"速度",1,100,cfg.speed,"",v->cfg.speed=v,()->changed());CheckBox reverse=new CheckBox(this);reverse.setText("反向");reverse.setTextColor(MUTED);reverse.setTextSize(12);reverse.setButtonTintList(ColorStateList.valueOf(ACCENT));reverse.setChecked(cfg.reverse);movement.addView(reverse,new LinearLayout.LayoutParams(dp(85),dp(58)));reverse.setOnCheckedChangeListener((v,x)->{cfg.reverse=x;changed();});controls.addView(movement);}
        String m=cfg.mode;if(m.equals("comet")||m.equals("chase")||m.equals("duet")||m.equals("sweep")||m.equals("bounce")||m.equals("rain")||m.equals("wave")||m.equals("sparkle")||m.equals("breathe")||m.equals("gradient"))section(Patterns.NAMES[Patterns.index(m)]+"设置");
        if(m.equals("comet"))slider(controls,"拖尾长度",1,24,cfg.tail," 格",v->cfg.tail=v,()->changed());
        if(m.equals("comet")||m.equals("chase")||m.equals("duet"))slider(controls,"光头柔和度",0,100,cfg.softness,"%",v->cfg.softness=v,()->changed());
        if(m.equals("sweep")||m.equals("bounce")||m.equals("rain"))slider(controls,"光带宽度",8,80,cfg.width,"%",v->cfg.width=v,()->changed());
        if(m.equals("wave"))slider(controls,"波峰数量",1,6,cfg.waves,"",v->cfg.waves=v,()->changed());
        if(m.equals("sparkle"))slider(controls,"星光密度",5,90,cfg.density,"%",v->cfg.density=v,()->changed());
        if(m.equals("breathe")||m.equals("gradient"))slider(controls,"最低亮度",0,80,cfg.floor,"%",v->cfg.floor=v,()->changed());
        if(categoryMusic){section("音乐输入");spinner(controls,new String[]{"麦克风 · 外部音乐","本机播放 · 其他应用"},cfg.source,v->{cfg.source=v;changed();});
            LinearLayout tune=new LinearLayout(this);LinearLayout gain=column(),release=column();tune.addView(gain,new LinearLayout.LayoutParams(0,-2,1));tune.addView(release,new LinearLayout.LayoutParams(0,-2,1));controls.addView(tune);slider(gain,"灵敏度",0,100,cfg.gain,"",v->cfg.gain=v,()->changed());slider(release,"回落柔和度",0,100,cfg.release,"%",v->cfg.release=v,()->changed());
            slider(controls,"弱音响应",30,85,cfg.gate,"",v->cfg.gate=v,()->changed());controls.addView(button("播放 3 秒测试节奏",Color.WHITE,MUTED,()->AudioInput.testTone()),new LinearLayout.LayoutParams(-1,dp(36)));
            TextView privacy=text("只实时分析音量，不保存录音。",11,MUTED);privacy.setPadding(0,dp(8),0,0);controls.addView(privacy);
        }
        building=false;
    }
    private void renderColorSlots(){if(colorSlots==null)return;colorSlots.removeAllViews();int[] colors=Patterns.colorStops(cfg);for(int n=0;n<colors.length;n++){final int index=n;int color=colors[n];double luma=Color.red(color)*.2126+Color.green(color)*.7152+Color.blue(color)*.0722;Button swatch=button(Patterns.hex(color),color,luma>155?INK:Color.WHITE,()->colorDialog(index));swatch.setTextSize(10);swatch.setContentDescription("颜色 "+(n+1)+"，点击选色");LinearLayout.LayoutParams layout=colors.length<4?new LinearLayout.LayoutParams(dp(105),dp(37)):cell(37);layout.setMargins(dp(3),dp(6),dp(3),dp(3));colorSlots.addView(swatch,layout);}if(colors.length<4){TextView hint=text("点色块选色",11,MUTED);hint.setGravity(Gravity.CENTER_VERTICAL);hint.setPadding(dp(8),0,0,0);colorSlots.addView(hint,new LinearLayout.LayoutParams(0,dp(48),1));}}
    private void resizeColors(int count){if(cfg.palette==13){int[] before=Patterns.parseColors(cfg.colors);if(count>before.length){int[] next=new int[count];for(int n=0;n<count;n++)next[n]=n<before.length?before[n]:Color.HSVToColor(new float[]{(float)(n*360.0/count),.9f,1});cfg.colors=Patterns.encode(next);}}cfg.colorCount=count;}
    private void colorDialog(int index){int[] stops=Patterns.colorStops(cfg);if(index>=stops.length)return;LinearLayout content=dialogContent();content.addView(text("拖动色轮选色，在中间调整浓淡和明暗。",12,MUTED));LinearLayout entry=new LinearLayout(this);View sample=new View(this);sample.setBackground(bg(stops[index],12));entry.addView(sample,new LinearLayout.LayoutParams(dp(43),dp(38)));EditText hex=new EditText(this);hex.setSingleLine(true);hex.setText(Patterns.hex(stops[index]));hex.setTextSize(15);entry.addView(hex,new LinearLayout.LayoutParams(0,dp(43),1));content.addView(entry);final ColorPickerView[] picker=new ColorPickerView[1];final boolean[] editing={false};
        picker[0]=new ColorPickerView(this,stops[index],color->{editing[0]=true;hex.setText(Patterns.hex(color));sample.setBackground(bg(color,12));editing[0]=false;});content.addView(picker[0],new LinearLayout.LayoutParams(-1,dp(185)));
        content.addView(button("随机颜色",LINE,INK,()->{java.util.Random random=new java.util.Random();int color=Color.rgb(random.nextInt(256),random.nextInt(256),random.nextInt(256));picker[0].setColor(color);hex.setText(Patterns.hex(color));sample.setBackground(bg(color,12));}),new LinearLayout.LayoutParams(-1,dp(36)));
        hex.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence c,int st,int n,int a){}public void afterTextChanged(android.text.Editable e){}public void onTextChanged(CharSequence c,int st,int before,int count){if(!editing[0])try{int color=Patterns.parseColors(c.toString())[0];picker[0].setColor(color);sample.setBackground(bg(color,12));}catch(Exception ignored){}}});
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("颜色 "+(index+1)).setView(content).setNegativeButton("取消",null).setPositiveButton("使用颜色",null).create();show(dialog);dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);dialog.getButton(-1).setOnClickListener(v->{try{int[] chosen=Patterns.parseColors(hex.getText().toString());if(chosen.length!=1)throw new IllegalArgumentException("这里输入一个颜色");int[] edited=cfg.palette==13?Patterns.parseColors(cfg.colors):stops;edited[index]=chosen[0];cfg.colors=Patterns.encode(edited);cfg.palette=13;cfg.colorCount=stops.length;dialog.dismiss();renderControls();changed();}catch(Exception e){hex.setError(e.getMessage());}});}
    private SeekBar slider(LinearLayout parent,String name,int min,int max,int initial,String suffix,IntConsumer value,Runnable update){
        LinearLayout box=column();box.setPadding(dp(3),dp(7),dp(5),0);TextView label=text(name+"  "+initial+suffix,12,MUTED);box.addView(label);SeekBar s=new SeekBar(this);s.setMax(max-min);s.setProgress(initial-min);s.setProgressTintList(ColorStateList.valueOf(ACCENT));s.setThumbTintList(ColorStateList.valueOf(ACCENT));box.addView(s,new LinearLayout.LayoutParams(-1,dp(30)));parent.addView(box);
        s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar v){}public void onStopTrackingTouch(SeekBar v){if(!building)update.run();}public void onProgressChanged(SeekBar v,int n,boolean fromUser){label.setText(name+"  "+(n+min)+suffix);if(fromUser){value.accept(n+min);if(!building)update.run();}}});return s;
    }
    private Spinner spinner(LinearLayout parent,String[] options,int selected,IntConsumer callback){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,options));s.setSelection(selected);s.setTag(false);s.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)s.setTag(true);return false;});parent.addView(s,new LinearLayout.LayoutParams(-1,dp(40)));s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int n,long id){if(Boolean.TRUE.equals(s.getTag())){s.setTag(false);callback.accept(n);}}});return s;}
    private final Runnable apply=()->applyRing(false);
    private void changed(){if(building)return;persist();ui.removeCallbacks(apply);ui.postDelayed(apply,90);}
    private void applyRing(boolean force){ui.removeCallbacks(apply);persist();if(!force&&!EffectsService.ringEnabled)return;dispatch(cfg.write(new Intent(this,EffectsService.class).putExtra("command","ring")));}
    private void dispatch(Intent i){if("off".equals(i.getStringExtra("command"))||"quit".equals(i.getStringExtra("command"))||"off".equals(i.getStringExtra("mode"))){ui.removeCallbacks(apply);ui.removeCallbacks(logoApply);}boolean logo="logo".equals(i.getStringExtra("command"));boolean need=logo?i.getIntExtra("logo_mode",EffectsService.logoMode)==3:(!"off".equals(i.getStringExtra("command"))&&!"quit".equals(i.getStringExtra("command"))&&(Patterns.music(i.getStringExtra("mode"))||prefs.getInt("logo_mode",2)==3));
        if(need&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){pending=i;requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);return;}startService(i);}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==7&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED&&pending!=null)startService(pending);else Toast.makeText(this,"音乐灯效需要音频权限",Toast.LENGTH_LONG).show();pending=null;}
    private void show(AlertDialog dialog){dialog.setOnDismissListener(d->immersive());dialog.show();dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);dialog.getWindow().getDecorView().setSystemUiVisibility(5894);dialog.getWindow().setBackgroundDrawable(bg(Color.WHITE,40));dialog.getWindow().getDecorView().setClipToOutline(true);dialog.getWindow().setLayout(Math.min(dp(520),getResources().getDisplayMetrics().widthPixels-dp(40)),-2);}
    private LinearLayout dialogContent(){LinearLayout box=column();box.setPadding(dp(22),dp(10),dp(22),dp(8));return box;}
    private void paletteDialog(){LinearLayout content=dialogContent();AlertDialog dialog=new AlertDialog.Builder(this).setTitle("选择配色").setView(content).setNegativeButton("返回",null).create();LinearLayout row=null;for(int n=0;n<Patterns.PALETTES.length;n++){if(n%4==0){row=new LinearLayout(this);content.addView(row);}final int p=n;Button choice=button(Patterns.PALETTES[n],cfg.palette==n?0xfff7dfe7:LINE,INK,()->{dialog.dismiss();if(p==13){customDialog();return;}cfg.palette=p;cfg.colorCount=Patterns.defaultCount(p);if(p>=10&&p<=12){cfg.bank=2;cfg.white=p==10?72:p==11?45:32;}renderControls();changed();});row.addView(choice,cell(43));}show(dialog);}
    private void customDialog(){LinearLayout content=dialogContent();content.addView(text("输入 1～8 个 HEX 颜色，用逗号或换行分隔。",12,MUTED));EditText input=new EditText(this);input.setText(Patterns.encode(Patterns.colorStops(cfg)));input.setTextSize(15);input.setMinLines(2);input.setMaxLines(3);content.addView(input);LinearLayout strip=new LinearLayout(this);content.addView(strip);TextView error=text("",12,ACCENT);content.addView(error);
        Runnable preview=()->{strip.removeAllViews();try{int[] stops=Patterns.parseColors(input.getText().toString());for(int color:stops){View v=new View(this);v.setBackground(bg(color,5));strip.addView(v,cell(20));}error.setText("");}catch(Exception e){error.setText(e.getMessage());}};
        input.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){preview.run();}public void afterTextChanged(android.text.Editable e){}});preview.run();
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("自定义色卡").setView(content).setNegativeButton("取消",null).setPositiveButton("使用色卡",null).create();show(dialog);dialog.getButton(-1).setOnClickListener(v->{try{Patterns.parseColors(input.getText().toString());cfg.colors=input.getText().toString().trim();cfg.palette=13;cfg.colorCount=Patterns.parseColors(cfg.colors).length;dialog.dismiss();renderControls();changed();}catch(Exception e){error.setText(e.getMessage());}});
    }
    private final Runnable logoApply=()->dispatch(new Intent(this,EffectsService.class).putExtra("command","logo").putExtra("logo_mode",prefs.getInt("logo_mode",2)).putExtra("logo_level",prefs.getInt("logo_level",96)));
    private void logoChanged(){ui.removeCallbacks(logoApply);ui.postDelayed(logoApply,90);}
    private void logoDialog(){LinearLayout content=dialogContent();content.addView(text("独立控制中间 Logo，环灯继续当前效果。",12,MUTED));spinner(content,new String[]{"关闭","固定亮度","跟随环灯","跟随音乐"},prefs.getInt("logo_mode",2),v->{prefs.edit().putInt("logo_mode",v).apply();logoChanged();});slider(content,"Logo 亮度",0,255,prefs.getInt("logo_level",96),"",v->prefs.edit().putInt("logo_level",v).apply(),()->logoChanged());show(new AlertDialog.Builder(this).setTitle("Logo 灯").setView(content).setPositiveButton("完成",null).create());}
    private void about(){startActivity(new Intent(this,AboutActivity.class));}
    private void quit(){show(new AlertDialog.Builder(this).setTitle("关闭软件").setMessage("关闭全部灯光，并结束后台灯效与音乐采集。").setNegativeButton("取消",null).setPositiveButton("关闭并退出",(d,w)->{ui.removeCallbacks(apply);ui.removeCallbacks(logoApply);dispatch(new Intent(this,EffectsService.class).putExtra("command","quit"));finishAndRemoveTask();}).create());}
    @Override public void onBackPressed(){moveTaskToBack(true);}
    private final Runnable refresh=new Runnable(){public void run(){if(dead)return;status.setText(EffectsService.status);status.setVisibility(EffectsService.ready?View.GONE:View.VISIBLE);ring.invalidate();boolean listening=EffectsService.audioListening&&EffectsService.running;audio.setText(listening?EffectsService.audioStatus+" · 音量 "+(int)(EffectsService.volume*100)+"%":"");audio.setVisibility(listening?View.VISIBLE:View.GONE);meter.setVisibility(listening?View.VISIBLE:View.GONE);meter.setProgress(listening?(int)(EffectsService.volume*100):0);runButton.setText(EffectsService.running?"关灯":"开灯");ui.postDelayed(this,80);}};
    @Override public void onDestroy(){dead=true;ui.removeCallbacksAndMessages(null);super.onDestroy();}
}
