package com.codex.ringlab;
import android.app.*;import android.content.Context;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Build;import android.view.*;import android.widget.*;
final class ReleaseNotes {
    private static int dp(Context c,float n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
    static void firstLaunch(Activity a){if(a.isFinishing())return;android.content.SharedPreferences p=a.getSharedPreferences("effects",0);if(p.getInt("changelog_seen",0)>=35)return;p.edit().putInt("changelog_seen",35).apply();show(a);}
    static void show(Activity a){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(dp(a,22),dp(a,18),dp(a,22),dp(a,12));TextView heading=new TextView(a);heading.setText("1.1 更新日志");heading.setTextSize(21);heading.setTextColor(0xff24364d);heading.setTypeface(Typeface.create("sans-serif-medium",0));box.addView(heading);ScrollView scroll=new ScrollView(a);scroll.setVerticalScrollBarEnabled(false);LinearLayout items=new LinearLayout(a);items.setOrientation(1);scroll.addView(items);
        String[] changes={"新图标与关于页","彩色光环应用图标，全屏卡片式关于页面，版本、作者、免费与免责说明集中展示。","操作更顺手","顶部分类对齐，选色新增随机按钮，开关灯合并为一个按钮。","短暂借用灯光","其他本机应用可调用内置效果、自定义 RGB／白灯和独立 Logo；用完默认恢复原灯效，主界面可随时接管。","更新与开发","关于页可检查最新版本或重新查看更新日志；接口文档、构建和硬件说明已独立整理。"};
        for(int i=0;i<changes.length;i++){TextView t=new TextView(a);t.setText(changes[i]);t.setTextSize(i%2==0?15:13);t.setTextColor(i%2==0?0xff24364d:0xff6e7e91);t.setLineSpacing(dp(a,3),1);if(i%2==0){t.setTypeface(Typeface.create("sans-serif-medium",0));t.setPadding(0,dp(a,15),0,dp(a,5));}items.addView(t);}
        LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,Math.min(dp(a,260),Math.round(a.getResources().getDisplayMetrics().heightPixels*.52f)));box.addView(scroll,sp);Button done=new Button(a);done.setText("知道了");done.setAllCaps(false);done.setTextSize(13);done.setTextColor(Color.WHITE);done.setMinHeight(0);done.setMinimumHeight(0);done.setPadding(dp(a,7),0,dp(a,7),0);GradientDrawable button=new GradientDrawable();button.setColor(0xffd85371);button.setCornerRadius(18*a.getResources().getDisplayMetrics().widthPixels/1600f);done.setBackground(button);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(a,38));bp.topMargin=dp(a,15);box.addView(done,bp);
        AlertDialog dialog=new AlertDialog.Builder(a).setView(box).create();done.setOnClickListener(v->dialog.dismiss());dialog.setOnDismissListener(v->a.getWindow().getDecorView().setSystemUiVisibility(5894));dialog.show();dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);dialog.getWindow().getDecorView().setSystemUiVisibility(5894);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(40*a.getResources().getDisplayMetrics().widthPixels/1600f);dialog.getWindow().setBackgroundDrawable(bg);dialog.getWindow().getDecorView().setClipToOutline(true);dialog.getWindow().setLayout(Math.min(dp(a,520),a.getResources().getDisplayMetrics().widthPixels-dp(a,60)),-2);
    }
}
