package com.codex.ringlab;
import android.app.*;import android.content.Context;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Build;import android.view.*;import android.widget.*;
final class ReleaseNotes {
    private static int dp(Context c,float n){return Math.round(n*c.getResources().getDisplayMetrics().density);}
    static void firstLaunch(Activity a){if(a.isFinishing())return;android.content.SharedPreferences p=a.getSharedPreferences("effects",0);if(p.getInt("changelog_seen",0)>=36)return;p.edit().putInt("changelog_seen",36).apply();show(a);}
    static void show(Activity a){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(dp(a,22),dp(a,18),dp(a,22),dp(a,12));TextView heading=new TextView(a);heading.setText("1.2 更新日志");heading.setTextSize(21);heading.setTextColor(0xff24364d);heading.setTypeface(Typeface.create("sans-serif-medium",0));box.addView(heading);ScrollView scroll=new ScrollView(a);scroll.setVerticalScrollBarEnabled(false);LinearLayout items=new LinearLayout(a);items.setOrientation(1);scroll.addView(items);
        String[] changes={"流光呼吸","新增呼吸与旋转结合的柔和光带，呼吸速度、旋转速度和光带宽度分别可调。","可调呼吸节奏","呼吸效果新增峰谷停留：越高越会在最亮与最暗处缓慢停留，0% 保持原呼吸节奏。","柔和归还灯光","其他应用调用结束后，保留最后显示的灯光状态，约 1.2 秒渐变回原灯效；彩灯、白灯与中间 Logo 一起过渡。","音乐页面布局","音量显示预留固定空间，Logo 设置与开关灯保持对齐，按钮间距统一。","关于页面","版本号 1.2 放在应用名下方居中显示。","接口兼容","沿用 v1 协议；正常归还、调用者退出、租约到期及关闭接口均支持柔和恢复。手动关灯和退出仍立即关闭。"};
        for(int i=0;i<changes.length;i++){TextView t=new TextView(a);t.setText(changes[i]);t.setTextSize(i%2==0?15:13);t.setTextColor(i%2==0?0xff24364d:0xff6e7e91);t.setLineSpacing(dp(a,3),1);if(i%2==0){t.setTypeface(Typeface.create("sans-serif-medium",0));t.setPadding(0,dp(a,15),0,dp(a,5));}items.addView(t);}
        LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,Math.min(dp(a,260),Math.round(a.getResources().getDisplayMetrics().heightPixels*.52f)));box.addView(scroll,sp);Button done=new Button(a);done.setText("知道了");done.setAllCaps(false);done.setTextSize(13);done.setTextColor(Color.WHITE);done.setMinHeight(0);done.setMinimumHeight(0);done.setPadding(dp(a,7),0,dp(a,7),0);GradientDrawable button=new GradientDrawable();button.setColor(0xffd85371);button.setCornerRadius(18*a.getResources().getDisplayMetrics().widthPixels/1600f);done.setBackground(button);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(a,38));bp.topMargin=dp(a,15);box.addView(done,bp);
        AlertDialog dialog=new AlertDialog.Builder(a).setView(box).create();done.setOnClickListener(v->dialog.dismiss());dialog.setOnDismissListener(v->a.getWindow().getDecorView().setSystemUiVisibility(5894));dialog.show();dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);dialog.getWindow().getDecorView().setSystemUiVisibility(5894);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(40*a.getResources().getDisplayMetrics().widthPixels/1600f);dialog.getWindow().setBackgroundDrawable(bg);dialog.getWindow().getDecorView().setClipToOutline(true);dialog.getWindow().setLayout(Math.min(dp(a,520),a.getResources().getDisplayMetrics().widthPixels-dp(a,60)),-2);
    }
}
